catch (int b)
    // {
    //     cout << "Positive Exception Block, value is: " << b << endl;
    // }